services:
  frontend:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    volumes:
      - ./ClientApp:/workspaces/ClientApp:cached
      - /workspaces/ClientApp/node_modules
    environment:
      - NODE_ENV=development
