services:
  angular-app:
    build:
      context: ./dogedex
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Map Nginx's port 80 to local port 4200
    volumes:
      - ./dist:/usr/share/nginx/html # Hot-reloading (optional)
    container_name: angular-app
